
GET http://localhost:5160

###

GET http://localhost:5160/api/categories
# GET http://localhost:5160/api/categories?searchValue=clothing

###

POST http://localhost:5160/api/categories
Content-Type: application/json 

{
  "name": "smart phone",
  "description": "good categiry"
}


###

PUT http://localhost:5160/api/categories/6c49cb58-9315-48ce-b6f2-95f41109858d
Content-Type: application/json 

{
  "name": "clothing",
  "description": "clothing is an essential category"
}


###

DELETE http://localhost:5160/api/categories/679e1f85-746e-4f8c-85c2-8ee2404f844f